# coding=utf-8
import psycopg2

conn = psycopg2.connect(
	host = "localhost",
	database = "proyecto",
	user = "postgres",
	port = 5433,
	password = "postpass")

cur = conn.cursor()

try:
#ANTENAS
	#cur.execute("create table Antenas(id int PRIMARY KEY, comuna varchar(255), tipo_frecuencia varchar(255), frecuencia float, anio_instalacion int, estado int, radio_cobertura int);") #usar query en SQL
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (1, 'Linares', '4G', 2.6, 2020, 1, 50); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (2, 'Niunioa', '3G', 2.1, 2019, 0, 30); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (3, 'Alto Hospicio', '5G', 6.0, 2021, 1, 10); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (4, 'Linares', '2G', 1.8, 1999, 1, 270); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (5, 'Alto Hospicio', '2G', 1.9, 2002, 1, 280); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (6, 'Alto Hospicio', '2G', 1.9, 2004, 1, 75); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (7, 'Coyhaique', '2G', 1.9, 2004, 1, 150); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (8, 'Alto Hospicio', '2G', 1.9, 2011, 1, 200); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (9, 'Linares', '2G', 1.9, 2017, 1, 230); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (10, 'Curacavi', '2G', 0.85, 2007, 1, 190); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (11, 'Frutillar', '4G', 2.6, 2000, 1, 30); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (12, 'Frutillar', '2G', 1.9, 2006, 1, 30); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (13, 'Puerto Montt', '4G', 2.6, 2000, 0, 10); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (14, 'Linares', '2G', 1.9, 2003, 1, 24); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (15, 'Linares', '2G', 1.9, 2018, 1, 48); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (16, 'Alto Hospicio', '2G', 1.9, 2007, 1, 30); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (17, 'Coyhaique', '4G', 2.6, 2011, 1, 30); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (18, 'Coyhaique', '2G', 1.9, 2003, 0, 40); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (19, 'Coyhaique', '2G', 1.8, 2003, 1, 50); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (20, 'Linares', '3G', 2.1, 2017, 1, 48); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (21, 'Niebla', '4G', 2.6, 2015, 1, 30); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (22, 'Coyhaique', '4G', 2.4, 2020, 0, 35); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (23, 'Los Angeles', '2G', 1.9, 2011, 1, 60); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (24, 'Curacavi', '3G', 2.0, 2012, 1, 56); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (25, 'Los Angeles', '2G', 1.8, 2016, 1, 60); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (26, 'Santiago', '3G', 2.1, 2021, 1, 28); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (27, 'Estacion Central', '2G', 1.9, 2015, 1, 75); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (28, 'Alto Hospicio', '4G', 2.6, 2019, 0, 39); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (29, 'Niunioa', '2G', 1.8, 2011, 1, 20); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (30, 'Niunioa', '2G', 1.8, 2005, 1, 20); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (31, 'Los Angeles', '2G', 1.4, 2006, 1, 70); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (32, 'San Rosendo', '4G', 2.2, 2021, 1, 40); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (33, 'Los Angeles', '2G', 1.4, 2000, 1, 75); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (34, 'Niunioa', '4G', 2.6, 2020, 0, 65); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (35, 'Niunioa', '2G', 1.8, 2011, 1, 40); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (36, 'Curacavi', '4G', 2.5, 2021, 1, 20); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (37, 'Coyhaique', '2G', 1.7, 2016, 1, 20); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (38, 'Niunioa', '2G', 2.0, 2018, 1, 70); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (39, 'Los Angeles', '2G', 1.4, 2015, 1, 65); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (40, 'Valparaiso', '4G', 2.4, 2020, 0, 55); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (41, 'Valdivia', '5G', 6.0, 2021, 1, 40); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (42, 'La Pintana', '2G', 1.6, 2007, 1, 69); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (43, 'Los Angeles', '2G', 1.4, 2016, 1, 20); ")#
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (44, 'Curacavi', '4G', 2.2, 2021, 1, 10); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (45, 'Niebla', '2G', 1.4, 2015, 1, 75); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (46, 'Coyhaique', '4G', 2.6, 2021, 0, 40); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (47, 'Los Angeles', '2G', 1.7, 2011, 1, 80); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (48, 'Niunioa', '3G', 2.1, 2020, 1, 29); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (49, 'Coyhaique', '4G', 2.6, 2018, 1, 40); ")
	#cur.execute("insert into Antenas(id, comuna, tipo_frecuencia, frecuencia, anio_instalacion, estado, radio_cobertura) values (50, 'Santiago', '5G', 5.9, 2021, 1, 40); ")


#EMPRESAS
	#cur.execute ("create table Empresas(rut varchar(20) PRIMARY KEY, nombre varchar(20));")
	#cur.execute (" insert into Empresas (RUT, nombre) values ('96.833.480-8', 'Will'); ")
	#cur.execute (" insert into Empresas (RUT, nombre) values ('76.136.972-5', 'Virgin Mobile'); ")#
	#cur.execute (" insert into Empresas (RUT, nombre) values ('78.921.690-8', 'WOM'); ")
	#cur.execute (" insert into Empresas (RUT, nombre) values ('96.799.250-K', 'Claro'); ")
	#cur.execute (" insert into Empresas (RUT, nombre) values ('90.635.000-9', 'Movistar'); ")
	#cur.execute (" insert into Empresas (RUT, nombre) values ('92.580.000-7', 'Entel'); ")
	#conn.commit()

#CONCESIONAN
	#cur.execute ("create table Concesionan(rut_empresa varchar(20), id_antena int);")
	#cur.execute ("insert into Concesionan(rut_empresa, id_antena) values ('96.833.480-8', 1); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('96.799.250-K', 2); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('92.580.000-7', 3); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('96.799.250-K', 4); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('96.799.250-K', 5); ")#
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('96.799.250-K', 6); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('96.799.250-K', 7); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('92.580.000-7', 8); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('96.799.250-K', 9); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('96.799.250-K', 10); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('78.921.690-8', 11); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('96.799.250-K', 12); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('78.921.690-8', 13); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('78.921.690-8', 14); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('96.799.250-K', 15); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('92.580.000-7', 16); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('78.921.690-8', 17); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('96.799.250-K', 18); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('90.635.000-9', 19); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('92.580.000-7', 20); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('96.799.250-K', 21); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('92.580.000-7', 22); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('96.799.250-K', 23); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('96.799.250-K', 24); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('96.799.250-K', 25); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('96.799.250-K', 26); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('90.635.000-9', 27); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('92.580.000-7', 28); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('76.136.972-5', 29); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('92.580.000-7', 30); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('90.635.000-9', 31); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('92.580.000-7', 32); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('76.136.972-5', 33); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('90.635.000-9', 34); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('90.635.000-9', 35); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('76.136.972-5', 36); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('92.580.000-7', 37); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('76.136.972-5', 38); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('90.635.000-9', 39); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('76.136.972-5', 40); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('76.136.972-5', 41); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('90.635.000-9', 42); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('78.921.690-8', 43); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('90.635.000-9', 44); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('92.580.000-7', 45); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('78.921.690-8', 46); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('78.921.690-8', 47); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('90.635.000-9', 48); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('96.799.250-K', 49); ")
	#cur.execute (" insert into Concesionan (RUT_EMPRESA, ID_ANTENA) values ('92.580.000-7', 50); ")
	#conn.commit()

#INVIERTEN
	#cur.execute ("create table Invierten(rut_empresa varchar(20), monto int, anio_inversion int, comuna varchar(255));")
	#cur.execute ("insert into Invierten(rut_empresa, monto, anio_inversion, comuna) values ('96.833.480-8', 2, 2008, 'Niebla'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('76.136.972-5', 4, 2005, 'Quillon'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('78.921.690-8', 1, 2020, 'Camarones'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('96.799.250-K', 8, 2001, 'Limache'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('90.635.000-9', 54, 2007, 'Santiago' ); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('90.635.000-9', 60, 2010, 'Valparaiso'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('96.833.480-8', 6, 2001, 'Concepcion'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('76.136.972-5', 9, 2018, 'Niunioa'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('78.921.690-8', 12, 2005, 'Hualanie'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('96.799.250-K', 8, 2001, 'Limache'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('90.635.000-9', 54, 2007, 'Santiago' ); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('90.635.000-9', 60, 2019, 'Valparaiso'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('96.833.480-8', 6, 2014, 'Maipu'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('76.136.972-5', 9, 2012, 'La Florida'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('78.921.690-8', 9, 2006, 'Tome'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('96.799.250-K', 10, 2003, 'Coyhaique'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('90.635.000-9', 5, 2002, 'Linares' ); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('90.635.000-9', 68, 2017, 'Arica'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('96.833.480-8', 7, 2004, 'Concon'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('76.136.972-5', 14, 2011, 'La Reina'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('78.921.690-8', 4, 2003, 'Requinoa'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('96.799.250-K', 2, 2019, 'Putre'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('90.635.000-9', 12, 2015, 'Putaendo' ); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('90.635.000-9', 1, 2002, 'Papudo'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('96.833.480-8', 33, 2013, 'Santiago'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('76.136.972-5', 17, 2016, 'Estacion Central'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('78.921.690-8', 6, 2006, 'Sagrada Familia'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('96.799.250-K', 4, 2009, 'San Rosendo'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('90.635.000-9', 24, 2007, 'Temuco'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('90.635.000-9', 16, 2021, 'Curacavi'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('96.833.480-8', 8, 2001, 'Zapallar'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('76.136.972-5', 3, 2018, 'Queilen'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('78.921.690-8', 2, 2005, 'Rinconada'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('96.799.250-K', 16, 2001, 'Angol'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('90.635.000-9', 17, 2007, 'Cerrillos'); ")
	#cur.execute (" insert into Invierten (RUT_EMPRESA, monto, anio_inversion, comuna) values ('90.635.000-9', 21, 2020, 'Quilicura'); ")

#ZONAS
	#cur.execute ("create table Zonas(comuna varchar(255) PRIMARY KEY, region varchar(255), num_region int, cant_habitantes int);")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Arica','Arica y Parinacota', 15, 50229); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Camarones','Arica y Parinacota', 15, 803); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Putre','Arica y Parinacota', 15, 208); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('General Lagos','Arica y Parinacota', 15, 64); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Iquique','Tarapaca', 1, 48208); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Alto Hospicio','Tarapaca', 1, 140); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Pozo Almonte','Tarapaca', 1, 50); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Camiña','Tarapaca', 1, 65); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Colchane','Tarapaca', 1, 30); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Huara','Tarapaca', 1, 25); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Pica','Tarapaca', 1, 39); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Antofagasta','Antofagasta', 2, 42008); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Mejillones','Antofagasta', 2, 350); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Sierra Gorda','Antofagasta', 2, 345); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Taltal','Antofagasta', 2, 5671); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Calama','Antofagasta', 2, 560); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Ollague','Antofagasta', 2, 190); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('San Pedro de Atacama','Antofagasta', 2, 100); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Tocopilla','Antofagasta', 2, 250); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Maria Elena','Antofagasta', 2, 302); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Copiapo','Atacama', 3, 14720); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Caldera','Atacama', 3, 143); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Tierra Amarilla','Atacama', 3, 45); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Chaniaral','Atacama', 3, 35); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Diego de Almagro','Atacama', 3, 320); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Vallenar','Atacama', 3, 180); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Alto del Carmen','Atacama', 3, 2340); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Freirina','Atacama', 3, 605); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Huasco','Atacama', 3, 1234); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('La Serena','Coquimbo', 4, 34234); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Coquimbo','Coquimbo', 4, 20060); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Andacollo','Coquimbo', 4, 309); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('La Higuera','Coquimbo', 4, 3098); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Paihuano','Coquimbo', 4, 430); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Vicuña','Coquimbo', 4, 209); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Illapel','Coquimbo', 4, 800); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Canela','Coquimbo', 4, 430); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Los Vilos','Coquimbo', 4, 5420); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Salamanca','Coquimbo', 4, 1092); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Ovalle','Coquimbo', 4, 3560); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Combarbala','Coquimbo', 4, 3401); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Monte Patria','Coquimbo', 4, 4321); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Punitaqui','Coquimbo', 4, 1243); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Rio Hurtado','Coquimbo', 4, 3456); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Valparaiso','Valparaiso', 5, 45689); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Casa Blanca','Valparaiso', 5, 8760); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Concon','Valparaiso', 5, 2305); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Juan Fernandez','Valparaiso', 5, 985); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Puchuncavi','Valparaiso', 5, 764); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Quintero','Valparaiso', 5, 203); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Vinia del Mar','Valparaiso', 5, 53004); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Isla de Pascua','Valparaiso', 5, 1020); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Los Andes','Valparaiso', 5, 543); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Calle Larga','Valparaiso', 5, 1200); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Rinconada','Valparaiso', 5, 850); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('San Esteban','Valparaiso', 5, 849); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('La ligua','Valparaiso', 5, 4875); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Cabildo','Valparaiso', 5, 5473); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Papudo','Valparaiso', 5, 875); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Petroca','Valparaiso', 5, 986); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Zapallar','Valparaiso', 5 , 394); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Quillota','Valparaiso', 5, 7549); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('La Calera','Valparaiso', 5, 392); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Hijuelas','Valparaiso', 5, 445); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('La Cruz','Valparaiso', 5, 666); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Nogales','Valparaiso', 5, 666); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('San Antonio','Valparaiso', 5, 666); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Algarrobo','Valparaiso', 5, 6564); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Cartagena','Valparaiso', 5, 856); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('El Quisco','Valparaiso', 5, 5666); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('El Tabo','Valparaiso', 5, 9584); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Santo Domingo','Valparaiso', 5, 103); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('San Felipe','Valparaiso', 5, 430); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Catemu','Valparaiso', 5, 490); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('LLay-LLay','Valparaiso', 5, 444); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Panquehue','Valparaiso', 5, 5043); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Putaendo','Valparaiso', 5, 4265); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Santa Maria','Valparaiso', 5, 876); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Quipue','Valparaiso', 5, 3450); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Limache','Valparaiso', 5, 3425); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Olmue','Valparaiso', 5, 25043); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Villa alemana','Valparaiso', 5, 987); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Rancagua','Libertador General Bernardo O_Higgins', 6, 32043); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Codegua','Libertador General Bernardo O_Higgins', 6, 876); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Coinco','Libertador General Bernardo O_Higgins', 6, 123); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Coltauco','Libertador General Bernardo O_Higgins', 6, 504); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Donihue','Libertador General Bernardo O_Higgins', 6, 390); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Graneros','Libertador General Bernardo O_Higgins', 6, 849); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Las Cabras','Libertador General Bernardo O_Higgins', 6, 504); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Machali','Libertador General Bernardo O_Higgins', 6, 123); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Malloa','Libertador General Bernardo O_Higgins', 6, 543); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Mostazal','Libertador General Bernardo O_Higgins', 6, 135); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Olivar','Libertador General Bernardo O_Higgins', 6, 234); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Peumo','Libertador General Bernardo O_Higgins', 6, 766); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Pichidegua','Libertador General Bernardo O_Higgins', 6, 342); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Quinta de Tilcoco','Libertador General Bernardo O_Higgins', 6, 345); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Rengo','Libertador General Bernardo O_Higgins', 6, 244); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Requinoa','Libertador General Bernardo O_Higgins', 6, 124); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('San Vicente','Libertador General Bernardo O_Higgins', 6, 564); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Pichilemu','Libertador General Bernardo O_Higgins', 6, 4780); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('La Estrella','Libertador General Bernardo O_Higgins', 6, 748); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Litueche','Libertador General Bernardo O_Higgins', 6, 123); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Marchihue','Libertador General Bernardo O_Higgins', 6, 432); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Navidad','Libertador General Bernardo O_Higgins', 6, 234); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Paredones','Libertador General Bernardo O_Higgins', 6, 203); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('San Fernando','Libertador General Bernardo O_Higgins', 6, 843); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Chepica','Libertador General Bernardo O_Higgins', 6, 135); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Chimbarongo','Libertador General Bernardo O_Higgins', 6, 409); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Lolol','Libertador General Bernardo O_Higgins', 6, 209); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Nancagua','Libertador General Bernardo O_Higgins', 6, 148); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Palmilla','Libertador General Bernardo O_Higgins', 6, 82); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Peralillo','Libertador General Bernardo O_Higgins', 6, 432); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Placilla','Libertador General Bernardo O_Higgins', 6, 398); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Pumanque','Libertador General Bernardo O_Higgins', 6, 1083); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Santa Cruz','Libertador General Bernardo O_Higgins', 6, 1280); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Talca','Maule', 7, 23049); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Constitucion','Maule', 7, 8390); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Curepto','Maule', 7, 2340); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Empedrado','Maule', 7, 213); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Maule','Maule', 7, 849); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Pelarco','Maule', 7, 543); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Pencahue','Maule', 7, 3290); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Rio Claro','Maule', 7, 324); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('San Clemente','Maule', 7, 4739); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('San Rafael','Maule', 7, 937); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Cauquenes','Maule', 7, 890); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Chanco','Maule', 7, 140); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Pelluhe','Maule', 7, 594); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Curico','Maule', 7, 33594); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Hualanie','Maule', 7, 748); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Licanten','Maule', 7, 5430); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Molina','Maule', 7, 4789); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Rauco','Maule', 7, 4830); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Romeral','Maule', 7, 2748); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Sagrada Familia','Maule', 7, 666); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Teno','Maule', 7, 3459); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Vichuqen','Maule', 7, 2349); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Linares','Maule', 7, 12716); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Colbun','Maule', 7, 3290); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Longavi','Maule', 7, 5403); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Parral','Maule', 7, 4903); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Retiro','Maule', 7, 849); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('San Javier','Maule', 7, 1293); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Villa Alegre','Maule', 7, 750); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Yerbas Buenas','Maule', 7, 430); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Chillan','Niuble', 16, 4999); ")
	#cur.execute ("in#sert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Bulnes','Niuble', 16, 930); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Chillan viejo','Niuble', 16, 1048); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('El Carmen','Niuble', 16, 918); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Pumeco','Niuble', 16, 489); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Pinto','Niuble', 16, 380); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Quillon','Niuble', 16, 4321); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('San Ignacio','Niuble', 16, 739); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Yungay','Niuble', 16, 459); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Quirihue','Niuble', 16, 1923); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Cobquecura','Niuble', 16, 948); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Ninhue','Niuble', 16, 606); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Portezuelo','Niuble', 16, 777); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Ranquil','Niuble', 16, 5345); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Treguaco','Niuble', 16, 654); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('San Carlos','Niuble', 16, 765); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Coihueco','Niuble', 16, 6789); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Niquen','Niuble', 16, 987); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('San Fabian','Niuble', 16, 764); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('San Nicolas','Niuble', 16, 1293); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Concepcion','Biobio', 8, 42500); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Coronel','Biobio', 8, 7890); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Chiguayante','Biobio', 8, 5830); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Florida','Biobio', 8, 5849); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Hualqui','Biobio', 8, 9241); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Lota','Biobio', 8, 792); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Penco','Biobio', 8, 893); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('San Pedro de La Paz','Biobio', 8, 4800); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Santa Juana','Biobio', 8, 6584); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Talcahuano','Biobio', 8, 820); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Tome','Biobio', 8, 830); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Hualpen','Biobio', 8, 4802); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Lebu','Biobio', 8, 9304); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Arauco','Biobio', 8, 795); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Caniete','Biobio', 8, 490); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Contulmo','Biobio', 8, 3849); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Curanilahue','Biobio', 8, 739); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Los Alamos','Biobio', 8, 1038); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Tirua','Biobio', 8, 483); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Los Angeles','Biobio', 8, 32309); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Antuco','Biobio', 8, 493); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Cabrero','Biobio', 8, 479); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Laja','Biobio', 8, 1739); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Mulchen','Biobio', 8, 109); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Nacimiento','Biobio', 8, 493); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Negrete','Biobio', 8, 948); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Quilaco','Biobio', 8, 473); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Quilleco','Biobio', 8, 239); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('San Rosendo','Biobio', 8, 2970); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Santa Barbara','Biobio', 8, 589); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Tucapel','Biobio', 8, 504); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Yumbel','Biobio', 8, 493); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Alto Biobio','Biobio', 8, 5870); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Temuco','La Araucania', 9, 53990); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Carahue','La Araucania', 9, 349); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Cunco','La Araucania', 9, 670); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Cararrehue','La Araucania', 9, 348); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Freire','La Araucania', 9, 429); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Galvino','La Araucania', 9, 473); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Gorbea','La Araucania', 9, 785); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Lautaro','La Araucania', 9, 666); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Loncoche','La Araucania', 9, 772); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Melipeuco','La Araucania', 9, 655); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Nueva Imperial','La Araucania', 9, 535); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Padre Las Casas','La Araucania', 9, 5432); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Perquenco','La Araucania', 9, 822); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Pitrufquen','La Araucania', 9, 2313); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Pucon','La Araucania', 9, 65321); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Saavedra','La Araucania', 9, 324); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Teodoro Schmidt','La Araucania', 9, 944); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Tolten','La Araucania', 9, 822); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Vilcun','La Araucania', 9, 424); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Villarrica','La Araucania', 9, 33033); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Cholchol','La Araucania', 9, 255); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Angol','La Araucania', 9, 733); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Collopullo','La Araucania', 9, 666); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Curacautin','La Araucania', 9, 343); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Ercilla','La Araucania', 9, 635); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Lonquimay','La Araucania', 9, 828); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Los Sauces','La Araucania', 9, 556); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Lumaco','La Araucania', 9, 998); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Puren','La Araucania', 9, 757); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Renaico','La Araucania', 9, 646); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Traiguen','La Araucania', 9, 833); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Victoria','La Araucania', 9, 1233); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Valdivia','Los Rios', 14, 43323); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Corral','Los Rios', 14, 1313); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Lanco','Los Rios', 14, 8276); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Los Lagos','Los Rios', 14, 455); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Mafil','Los Rios', 14, 771); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Mariquina','Los Rios', 14, 544); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Paillaco','Los Rios', 14, 976); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Panguipulli','Los Rios', 14, 6517); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('La Union','Los Rios', 14, 312); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Futrono','Los Rios', 14, 1198); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Lago Ranco','Los Rios', 14, 322); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Rio Bueno','Los Rios', 14, 1344); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Puerto Montt','Los Lagos', 10, 5655); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Calbuco','Los Lagos', 10, 2309); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Cochamo','Los Lagos', 10, 332); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Fresia','Los Lagos', 10, 444); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Frutillar','Los Lagos', 10, 777); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Los Muermos','Los Lagos', 10, 423); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Llanquihue','Los Lagos', 10, 3126); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Maullin','Los Lagos', 10, 459); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Puerto Varas','Los Lagos', 10, 532); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Castro','Los Lagos', 10, 266); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Ancud','Los Lagos', 10, 842); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Chonchi','Los Lagos', 10, 433); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Curaco de Velez','Los Lagos', 10, 566); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Dalcahue','Los Lagos', 10, 852); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Puqueldon','Los Lagos', 10, 632); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Queilen','Los Lagos', 10, 366); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Quellon','Los Lagos', 10, 752); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Quemchi','Los Lagos', 10, 144); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Quinchao','Los Lagos', 10, 543); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Osorno','Los Lagos', 10, 4869); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Puerto Octay','Los Lagos', 10, 853); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Purranque','Los Lagos', 10, 459); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Rio Negro','Los Lagos', 10, 543); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('San Juan de la Costa','Los Lagos', 10, 422); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('San Pablo','Los Lagos', 10, 388); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Chaiten','Los Lagos', 10, 697); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Frutaleufu','Los Lagos', 10, 421); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Hualaihue','Los Lagos', 10, 822); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Palena','Los Lagos', 10, 123); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Coyhaique','Aysen', 11, 3961); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Lago Verde','Aysen', 11, 267); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Aysen','Aysen', 11, 641); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Cisnes','Aysen', 11, 475); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Guaitecas','Aysen', 11, 134); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Cochrane','Aysen', 11, 654); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('O_Higgins','Aysen', 11, 211); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Tortel','Aysen', 11, 598); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Chile Chico','Aysen', 11, 156); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Rio Ibañez','Aysen', 11, 332); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Punta Arenas','Magallanes y Antartica Chilena', 12, 2341); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Laguna Blanca','Magallanes y Antartica Chilena', 12, 543); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Rio Verde','Magallanes y Antartica Chilena', 12, 131); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('San Gregorio','Magallanes y Antartica Chilena', 12, 139); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Cabo de Hornos','Magallanes y Antartica Chilena', 12, 99); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Antartica','Magallanes y Antartica Chilena', 12, 27); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Porvenir','Magallanes y Antartica Chilena', 12, 401); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Primavera','Magallanes y Antartica Chilena', 12, 107); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Timaukel','Magallanes y Antartica Chilena', 12, 300); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Natales','Magallanes y Antartica Chilena', 12, 876); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Torres del Paine','Magallanes y Antartica Chilena', 12, 280); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Santiago','Metropolitana de Santiago', 13, 10141); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Cerrillos','Metropolitana de Santiago', 13, 4444); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Cerro Navia','Metropolitana de Santiago', 13, 8339); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Conchali','Metropolitana de Santiago', 13, 7220); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('El Bosque','Metropolitana de Santiago', 13, 6110); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Estacion Central','Metropolitana de Santiago', 13, 8544); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Huechuraba','Metropolitana de Santiago', 13, 322); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Independencia','Metropolitana de Santiago', 13, 4661); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('La Cisterna','Metropolitana de Santiago', 13, 4522); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('La Florida','Metropolitana de Santiago', 13, 9590); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('La Granja','Metropolitana de Santiago', 13, 4467); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('La Pintana','Metropolitana de Santiago', 13, 3876); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('La Reina','Metropolitana de Santiago', 13, 2331); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Las Condes','Metropolitana de Santiago', 13, 4322); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Lo Barnechea','Metropolitana de Santiago', 13, 556); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Lo Espejo','Metropolitana de Santiago', 13, 543); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Lo Prado','Metropolitana de Santiago', 13, 1123); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Macul','Metropolitana de Santiago', 13, 2233); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Maipu','Metropolitana de Santiago', 13, 8653); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Niunioa','Metropolitana de Santiago', 13, 3322); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Pedro Aguirre Cerda','Metropolitana de Santiago', 13, 7651); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Penialolen','Metropolitana de Santiago', 13, 4421); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Providencia','Metropolitana de Santiago', 13, 5123); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Pudahuel','Metropolitana de Santiago', 13, 7554); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Quilicura','Metropolitana de Santiago', 13, 5115); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Quinta Normal','Metropolitana de Santiago', 13, 2233); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Recoleta','Metropolitana de Santiago', 13, 6732); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Renca','Metropolitana de Santiago', 13, 422); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('San Joaquin','Metropolitana de Santiago', 13, 5643); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('San Miguel','Metropolitana de Santiago', 13, 1234); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('San Ramon','Metropolitana de Santiago', 13, 4500); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Vitacura','Metropolitana de Santiago', 13, 1980); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Puente Alto','Metropolitana de Santiago', 13, 765); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Pirque','Metropolitana de Santiago', 13, 3131); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Colina','Metropolitana de Santiago', 13, 3421); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Lampa','Metropolitana de Santiago', 13, 1244); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Til Til','Metropolitana de Santiago', 13, 1570); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('San Bernando','Metropolitana de Santiago', 13, 4097); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Buin','Metropolitana de Santiago', 13, 3865); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Calera de Tango','Metropolitana de Santiago', 13, 376); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Paine','Metropolitana de Santiago', 13, 5123); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Melipilla','Metropolitana de Santiago', 13, 3411); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Alhue','Metropolitana de Santiago', 13, 1321); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Curacavi','Metropolitana de Santiago', 13, 4122); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Maria Pinto','Metropolitana de Santiago', 13, 1313); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('San Pedro','Metropolitana de Santiago', 13, 2211); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Talagante','Metropolitana de Santiago', 13, 1122); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('El Monte','Metropolitana de Santiago', 13, 2732); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Isla de Maipo','Metropolitana de Santiago', 13, 1200); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Padre Hurtado','Metropolitana de Santiago', 13, 3320); ")
	#cur.execute ("insert into Zonas(COMUNA, region, num_region, cant_habitantes) values ('Peniaflor','Metropolitana de Santiago', 13, 8500); ")

#SELECT
	#cur.execute ("select * from test;")
	conn.commit() #si es insert, update o create
	#resultado = cur.fetchall() #si es un select
	#print resultado
except:
	print ("no puedo ejecutar esto")

cur.close()
conn.close()
